version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    
  rag-app:
    build: .
    volumes:
      - ./app:/app
      - ./data/obsidian_vault:/data/obsidian_vault
      - ./storage/vector_db:/storage/vector_db
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    command: tail -f /dev/null  # Keeps container running for development

volumes:
  ollama_data: