database:
  host: localhost
  port: 5432
  name: data_analytics_dev
  pool_size: 5

logging:
  level: DEBUG
  file: logs/development.log

services:
  google:
    rate_limit: 100
  crypto:
    rate_limit: 50
  health:
    check_interval: 300
