database:
  host: timescaledb
  port: 5432
  name: data_analytics_prod
  pool_size: 20

logging:
  level: INFO
  file: logs/production.log

services:
  google:
    rate_limit: 1000
  crypto:
    rate_limit: 500
  health:
    check_interval: 60
